base/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.home, name='home'),
    path('all-topics/', views.topics_page, name='topics'),
    path('all-rooms/', views.rooms_page, name='rooms'),
    path('all-activities/', views.activitiess_page, name='activities'),
    path('create-room/', views.create_room, name='create-room'),
    path('room-room/<str:pk>', views.display_room, name='room-room'),
    path('update-room/<str:pk>', views.update_room, name='update-room'),
    path('delete-room/<str:pk>', views.delete_room, name='delete-room'),
    
    path('delete-message/<str:pk>', views.delete_message, name='delete-message'),
    path('update-message/<str:pk>', views.update_message, name='update-message'),
    path('user-profile/<str:pk>', views.user_profile, name='user-profile'),
    path('update-profile/', views.update_profile, name='update-profile'),
    
    path('login/', views.login_user, name='login'),
    path('register/', views.register_user, name='register'),
    path('logout/', views.logout_user, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):
    name = models.CharField(verbose_name='Full Name',max_length=200,null=True)
    email=models.EmailField(unique=True,verbose_name='Email Address',max_length=254)
    image = models.ImageField(default='avatar.svg',null=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    bio = models.TextField(null=True)
    
class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=100,verbose_name='Group Name')
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    description = models.TextField(max_length=1000, blank=True,null=True)
    participants = models.ManyToManyField(User,related_name='participants',blank=True)
    # likes = models.IntegerField()
    # likes = models.ManyToManyField(User,related_name='likes',blank=True)
    
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    # class Meta:
    #     ordering=['-updated','-created']

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering=['-updated','-created']
    def __str__(self):
        return self.body[0:50]



base/templates/base/activity_comp.html
<style>
  #a{
    margin-left:45%;
  }
  .activities,.activities__header,.activities__box,.h2{
    background:linear-gradient(#000e2e,#004f5a);
    background-position: center;
    background-repeat: no-repeat;
  }
</style>
{% load static %}
<div class="activities">
  <div class="activities__header" >
    <h2 class='h2'>Recent Actions</h2>
  </div>
  {% for mes in room_mess %}
  <div class="activities__box">
    <div class="activities__boxHeader roomListRoom__header">
      <a href="{% url "user-profile" mes.user.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="{{mes.user.image.url}}" >
        </div>
        <p>
          @{{mes.user.username}}
          <span>{{mes.created|timesince}} ago</span>
        </p>
      </a>
      <div class="roomListRoom__actions">
        {% if request.user == mes.user %}
        <a href="{% url "delete-message" mes.id %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>remove</title>
            <path
              d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
            ></path>
          </svg>
        </a>
        {% endif %}
      </div>
    </div>
    <div class="activities__boxContent">
      <p>replied to post “<a href="{% url "room-room" mes.room.id %}">{{mes.room}}</a>”</p>
      <div class="activities__boxRoomContent">
        {{mes.body}}
      </div>
    </div>
  </div>
{% endfor %}
<a class="btn btn--link" id='a' href="{% url "activities" %}">
  More
  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
    <title>Open Activities Page</title>
    <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
  </svg>
</a>
</div>

base/templates/base/delete.html
{% extends "main.html" %}
{% block content %}
<style>
    .layout__box{
      background:linear-gradient(#000e2e,#004f5a);
      background-position: center;
      background-repeat: no-repeat;
  }
  .layout__boxHeader{
    background:linear-gradient(#000e2e,#004f5a);
    background-position: center;
    background-repeat: no-repeat;
  }
  </style>
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{ request.META.HTTP_REFERER }}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method='POST'>
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{OBJECT}}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

base/templates/base/delete_old.html
{% extends "main.html" %}

{% block content %}
<style>
    .confirmation-container {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 50vh;
    }
    .confirmation-box {
        border: 1px solid #ccc;
        padding: 20px;
        border-radius: 10px;
        background-color: #f8f9fa;
        box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        max-width: 800px;
        width: auto;
        text-align: center;
    }
    .confirmation-box p {
        font-size: 18px;
        margin-bottom: 20px;
    }
    .confirmation-box a,

    .confirmation-box a {
        text-decoration: none;
        color: black;
    }
    .confirmation-box a:hover {
        
        border-color: #545b62;
    }
    .confirmation-box input[type="submit"] {
        color: #fff;
        border: 1px solid #dc3545;
        cursor: pointer;
    }
    .confirmation-box input[type="submit"]:hover {
        background-color: #c82333;
        border-color: #bd2130;
    }
    .form-group{
        display: flex;
        justify-content: space-between;
    }
</style>
<div class="confirmation-container">
    <div class="confirmation-box">
        <form action="" method="POST">
            {% csrf_token %}
            <p>Are you sure you want to delete " <b>{{ OBJECT }}</b> "?</p>
           <div class="form-group">
            <a href="{{ request.META.HTTP_REFERER }}"><button type="button" class='btn btn-success'>Cancel</button></a>
            <button type="submit" class='btn btn-warning'>Confrim</button>
           </div>
        </form>
    </div>
</div>
{% endblock  %}

base/templates/base/edit-user.html
{% extends "main.html" %}
{% block content %}
<style>
    .layout__box{
        height:88vh;
        background:linear-gradient(#000e2e,#004f5a);
        background-position: center;
        background-repeat: no-repeat;
    }
    .layout__boxHeader{
        background:linear-gradient(#000e2e,#004f5a);
        background-position: center;
        background-repeat: no-repeat;
    }
    .form .form__group{
        margin-top:-20px;
    }
    @media screen and (max-width: 900px) {
        .layout__box{
            height:95vh
        }
    }
</style>
    <main class="update-account layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{ request.META.HTTP_REFERER }}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method='POST'  enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for field in form %}

                        <div class="form__group">
                            <label for="profile_pic">{{field.label}}</label>
                            {{field}}
                        </div>
                            {% endfor %}
    
                        <div class="form__action">
                            <a class="btn btn--dark" href="{{ request.META.HTTP_REFERER }}">Cancel</a>
                            <button class="btn btn--main" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
    </main>
    {% endblock  %}

base/templates/base/feed_comp.html
<style>
  .roomListRoom{
    margin-top:-2%;
  }
  #a{
    margin-left:45%;
  }
</style>
{% load static %}
{% for room in rooms %}
<div class="roomListRoom"  style='
            background:linear-gradient(#000e2e,#004f5a);
            background-position: center;
            background-repeat: no-repeat;'>
  <div class="roomListRoom__header">
    <a href="{% url "user-profile" room.host.id %}" class="roomListRoom__author">
      {% if user.is_authenticated %}
        <div class="avatar avatar--small active">
          <img src="{{room.host.image.url}}" >
        </div>
      {% else %}
        <div class="avatar avatar--small">
          <img src="{{room.host.image.url}}" >
        </div>
      {% endif %}
      <span>@{{room.host.username}}</span>
    </a>
   
    <div class="roomListRoom__actions">
      <span>{{room.created|timesince}} ago</span>
    </div>
    {% if request.user == room.host %}
    <div class="room__topRight">
      <a href="{% url "update-room" room.id %}">
        <svg
          enable-background="new 0 0 24 24"
          height="32"
          viewBox="0 0 24 24"
          width="18"
          xmlns="http://www.w3.org/2000/svg"
        >
          <title>edit</title>
          <g>
            <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
          </g>
          <g>
            <g>
              <path
                d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
              />
            </g>
            <g>
              <path
                d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
              />
            </g>
          </g>
        </svg>
      </a>
      <a href="{% url "delete-room" room.id %}">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="18" height="32" viewBox="0 0 32 32">
          <title>remove</title>
          <path
            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
          ></path>
        </svg>
      </a>
    </div>
    {% endif %}
  </div>
  <div class="roomListRoom__content">
    <a href="{% url "room-room" room.id %}">{{room.name}}</a>
    <p>
   {{room.description}}
    </p>
  </div>
 
  <div class="roomListRoom__meta">
    <a href="{% url "home" %}" class="roomListRoom__joined">
      <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>user-group</title>
        <path
          d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
        ></path>
        <path
          d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
        ></path>
        <path
          d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
        ></path>
        <path
          d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
        ></path>
      </svg>
      {{room.participants.all.count}} Joined
    </a>
    {% comment %} <a href="">❤ &nbsp;<span>{{room.participants.all.count}}</span></a> {% endcomment %}
    <p class="roomListRoom__topic">{{room.topic}}</p>
  </div>
</div>
{% endfor %}


base/templates/base/home.html
{% extends "main.html" %}
{% block content %}
<style>
  @media screen and (max-width: 900px) {
    .body{
      display: flex;
      flex-direction:column;
      width: 100%;
      justify-content: center;
      margin-left:2%;
      background-size:cover;
    }
  }
  .p{
    color:chartreuse;
    font-weight:bold;
    font-size:20px;
    text-align:center;
  }
</style>
{% for mes in messages %}
  <div class="alert alert-success mt-3" role="alert">
    <p class="p">{{ mes }}</p>
  </div>
{% endfor %}
    <main class="layout layout--3">

      <div class="container">
        <!-- Topics Start -->
        {% include "base/topics_comp.html" %}
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
          <div class="mobile-menu">
            <form class="header__search"  method='GET' action='{% url "home" %}'>
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for rooms..."  name='q' />
              </label>
            </form>
            <div class="mobile-menuItems">
              <a class="btn btn--main btn--pill" href="{% url "topics" %}">Browse Topics</a>
              <a class="btn btn--main btn--pill" href="{% url "activities" %}">Recent Activities</a>
            </div>
          </div>
          <div class="roomList__header">
            <div>
              <h2>Study Groups</h2>
              <p>{{rooms_count}} Groups available</p>
            </div>
            <a class="btn btn--main" href="{% url "create-room" %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>add</title>
                <path
                  d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                ></path>
              </svg>
              Create Study Group
            </a>
          </div>
          {% include "base/feed_comp.html" %}
          <a class="btn btn--link" id='a' href="{% url "rooms" %}">
            More
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>View All Available Groups</title>
              <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
            </svg>
          </a>
        </div>
        <!-- Room List End -->

        <!-- Activities Start -->
        {% include "base/activity_comp.html" %}
        <!-- Activities End -->
      </div>
    </main>
    <script src="script.js"></script>
{% endblock %}

base/templates/base/login_register_old.html
{% extends "main.html" %}

{% block content %}
{% if page == 'login' %}
    <div>
        <div>
            {% for mess in messages %}
                <p>{{mess}}</p>
            {% endfor %}
        </div>
        <form action="" method="post">
            {% csrf_token %}
            <label for="">Username</label>
            <input type="text" name="username" id="" placeholder='username'>
            <label for="">Password</label>
            <input type="password" name="password" id="" placeholder='password'>
            <button type="submit">Login</button>
        </form>
        <p>Haven't signed up Yet?</p>
        <a href="{% url "register" %}">Sign Up</a>
    </div>
{% else %}
    <div>
        <div>
            {% for mess in messages %}
                <p>{{mess}}</p>
            {% endfor %}
        </div>
        <form action="" method="post">
            {% csrf_token %}
           {{form.as_p}}
            <button type="submit">Register</button>
        </form>
        <p>Already signed up Yet?</p>
        <a href="{% url "login" %}">Login</a>
    </div>
    {% endif %}
{% endblock  %}

base/templates/base/profile.html
{% extends "main.html" %}
{% load static %}
{% block content %}

  <main class="profile-page layout layout--3">
    <div class="container">
      <!-- Topics Start -->
      {% include "base/topics_comp.html" %}
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              {% if user.image %}
              <img src="{{user.image.url}}" >
              {% else %}
              <img src="{% static "images/avatar.svg" %}" alt="tyui">
              {% endif %}
            </div>
          </div>
          <div class="profile__info">
            <h3>{{user.name}}</h3>
            <p>@{{user.username}}</p>
            
            {% if user == request.user %}
              <p>Active now</p>
              <a href="{% url "update-profile" %}" class="btn btn--main btn--pill">Edit Profile</a>
            {% else %}
              <p>Active {{user.last_login|timesince}} ago</p>
            {% endif %}
            
          </div>
          <div class="profile__about">
            <h3>About</h3>
            <p>
              {{user.bio}}
            </p>
          </div>
        </div>

        {% include "base/feed_comp.html" %}
        <a class="btn btn--link" id='a' href="{% url "rooms" %}">
          More
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>chevron-down</title>
            <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
          </svg>
        </a>
      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      {% include "base/activity_comp.html" %}
      <!-- Activities End -->
    </div>
  </main>
{% endblock %}

base/templates/base/profile_old.html
{% extends "main.html" %}
{% block content %}
<style>
    .contt{
        display: grid;
        grid-template-columns:1fr 3fr 1fr;
    }
</style>
 <h1>{{user.username}}</h1>
<div class="contt">
    <div>
        {% include "base/topics_comp.html" %}
     </div>
     <div>
        {% include "base/feed_comp.html" %}
     </div>
     <div>
        {% include "base/activity_comp.html" %}
     </div>
</div>
{% endblock  %}

base/templates/base/room_details.html
{% extends "main.html" %}
{% load static %}
{% block content %}
<style>
  .room,.room__top,.participants__top{
    background:linear-gradient(#000e2e,#004f5a);
    background-position: center;
    background-repeat: no-repeat;
}
.layout__boxHeader{
  background:linear-gradient(#000e2e,#004f5a);
  background-position: center;
  background-repeat: no-repeat;
}
</style>
    <main class="profile-page layout layout--2">
      <div class="container">
        <!-- Room Start -->
        <div class="room">
          <div class="room__top">
            <div class="room__topLeft">
              <a href="{{request.META.HTTP_REFERER}}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Study Room</h3>
            </div>
          
            
          </div>
          <div class="room__box scroll">
            <div class="room__header scroll" style='
             background:linear-gradient(#000e2e,#004f5a);
              background-position: center;
              background-repeat: no-repeat;
            '>
              <div class="room__info">
                <h3>{{room.name}}</h3>
                <span>{{room.created|timesince}} ago</span>
              </div>
              <div class="room__hosted">
                <p>Hosted By {{room.host.name}}</p>
                <a href="{% url "user-profile" room.host.id %}" class="room__author">
                  <div class="avatar avatar--small">
                    <img src="{{room.host.image.url}}" >
                  </div>
                  <span>@{{room.host.username}}</span>
                </a>
              </div>
              <div class="room__details">
              {{room.description}}
              </div>
              <span class="room__topics">{{room.topic}}</span>
            </div>
            <div class="room__conversation" >
              <div class="threads scroll"  style='
              background:linear-gradient(#000e2e,#004f5a);
               background-position: center;
               background-repeat: no-repeat;
             '>
                {% for mes in Messages %}
                <div class="thread">
                  <div class="thread__top">
                    <div class="thread__author">
                      <a href="{% url "user-profile" request.user.id %}" class="thread__authorInfo">
                        <div class="avatar avatar--small">
                          <img src="{{mes.user.image.url}}" >
                        </div>
                        <span>@{{mes.user.username}}</span>
                      </a>
                      <span class="thread__date">{{mes.created|timesince}} ago</span>
                    </div>
                    {% if request.user == mes.user %}
                 <a href="{% url "delete-message" mes.id %}">
                  <div class="thread__delete">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                      <title>remove</title>
                      <path
                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                      ></path>
                    </svg>
                  </div>
                 </a>
                    {% endif %}
                  </div>
                  <div class="thread__details">
                    {{mes.body}}
                  </div>
                </div>
                <hr>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="room__message">
            {% if user.is_authenticated %}
            <form action="#" method="post">
              {% csrf_token %}
              <input  style='
              background:linear-gradient(#000e2e,#004f5a);
               background-position: center;
               background-repeat: no-repeat;
               border:3px solid grey;
             ' name="comment" placeholder="Write your message here..." />
            </form>
            {% endif %}
          </div>
        </div>
        <!-- Room End -->

        <!--   Start -->
        <div class="participants">
          <h3 class="participants__top">Participants <span>( {{room.participants.all.count}} )</span></h3>
          <div class="participants__list scroll" style='
          background:linear-gradient(#000e2e,#004f5a);
           background-position: center;
           background-repeat: no-repeat;
         '>
            {% for user in participants %}
            <a href="{% url "user-profile" user.id %}" class="participant">
              <div class="avatar avatar--medium">
                <img src="{{user.image.url}}" >
              </div>
              <p>
                {{user.name}}
                <span>@{{user.username}}</span>
              </p>
            </a>
            {% endfor %}
          </div>
        </div>
        <!--  End -->
      </div>
    </main>
{% endblock %}

base/templates/base/topics.html
{% extends "main.html" %}
{% block content %}
<style>
  .layout__box,.layout__boxHeader,.label{
    background:linear-gradient(#000e2e,#004f5a);
    background-position: center;
    background-repeat: no-repeat;
  }
  .s{
    color:chartreuse;
  }
</style>
    <main class="create-room layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url "home" %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Browse Topics (Total {{topics_count}})</h3>
            </div>
          </div>

          <div class="topics-page layout__body">
            <form class="header__search" method='GET' action='{% url "topics" %}'>
              <label class='label'>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input placeholder="Search for topics..."  name='q' />
              </label>
            </form>
            <h4><span>Results ({{topics.count}}) topics</span></h4>
            <ul class="topics__list">
          
              {% for topic in topics %}
              <li>
                <a href="{% url "home" %}?q={{topic.name}}">{{topic.name}}  <span title='Groups With Similar Topic' class='s'>{{topic.room_set.all.count}}</span></a>
              </li>
          {% endfor %}
          
            </ul>
          </div>
        </div>
      </div>
    </main>
    
{% endblock %}

base/templates/base/updatemess.html
{% extends 'main.html' %}
{% load crispy_forms_tags %}
  {% block content %}
    <h2>Update Message</h2>
<form action="" method="post">
    {% csrf_token %}
    {{form|crispy}}
    <button type="submit" class="btn btn-primary">Update</button>
</form>
 {% endblock %}